config/routes.rb
PIS::Application.routes.draw do

  get "appointment/calendar"
  post "patient/create"
  get "users/sign_out"
  get "welcome/new"

  devise_for :users
  resources :patient
  resources :patient do
    member do
      resources :information
      get "set_appointment"
      post "update"
      get "edit_image"
      patch "update_image"
    end
  end
  resources :appointment, as: 'appointments'
  root 'patient#startup'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :patient
  belongs_to :user
  has_many :services
  has_many :products, through: :services
end

app/controllers/appointment_controller.rb
class AppointmentController < ApplicationController
  before_action :find_appointment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @appointment = Appointment.joins(:patient).where("DATE(appointment_date) = '#{Date.today}'")
  end

  def create
    @appointment=current_user.appointment.build(appointment_params)
    @appointment.user_id = current_user.id
    if @appointment.save
      flash[:alert]="<big><span class='glyphicon glyphicon-book'></span></big> Appointment added."
      if current_user.role=="patient"
        redirect_to patient_path(@appointment.patient_id)
      else
        redirect_to appointments_path
      end
    else
      flash[:error]="<big><span class='glyphicon glyphicon-book'></span></big> Appointment not added."
      render 'new'
    end
  end

  def calendar
    @appointment = Appointment.select('concat(lname,", ",fname," ", left(mi,1),".") as title, appointment_date as start, patient_id').joins('left join patients on appointments.patient_id = patients.id')
    @ev = ""
    @events = "" 
    @appointment.each do |e|
      @ev << "{ title : '#{e.title}', start : '#{e.start.strftime("%F")}', url: '/patient/#{e.patient_id}'},"
    end
    @events << "[" << @ev.chop << "]"
  end  

  def update
    if @appointment.update(appointment_params)
      flash[:alert]="<big><span class='glyphicon glyphicon-book'></span></big> Appointment updated."
      redirect_to appointments_path
    else
      render 'edit'
    end
  end

  def destroy
    @appointment.destroy
    flash[:alert]="<big><span class='glyphicon glyphicon-book'></span></big> Appointment Cancelled."
    redirect_to appointments_path
  end

  def show
    @patient = Patient.find(@appointment.patient_id)
    @product=Product.all
  end
  
  def new
    @appointment = current_user.appointment.build
    @appointment.services.build
    @patient_name = "Please Select.."
    @mode = "Walk In"
    @product=Product.all
  end

  def edit

  end

  private

  def find_appointment
   @appointment = Appointment.find(params[:id]) 
  end

  def appointment_params
   params.require(:appointment).permit(:patient_id, :purpose, :appointment_date, :mode, :product_ids=>[])
  end
end

app/helpers/appointment_helper.rb
module AppointmentHelper
end

app/views/appointment/_backupcheckbox.html.erb
<%= f.fields_for :services do |g| %>
				<%= g.collection_check_boxes(:appointment, Product.all, :id, :name) do |b| %>
				<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
					<%= b.check_box(class: "check_box") %>
					<%= b.object.name %>
				</div>
				<% end %>
				<% end %>

app/views/appointment/_form.html.erb
<%= simple_form_for (@appointment), wrapper: :pis_form, wrapper_mappings: { pis: :pis_form, file: :vertical_file_input, mi: :pis_form_small } do |f| %>
<%= f.hidden_field :mode, :value=> @mode %>
<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
		<div class="form-group">
			<label>Patient Name<%= @method %></label>
			<% if @patient %>
			<%= f.select :patient_id, options_from_collection_for_select(Patient.all, :id, :fullname,@patient.id), {:prompt => @patient_name}, {:class => 'form-control'} %>
			<!--%= f.text_field :patient_name, value: @patient_name, class: 'form-control' %-->
			<% else %>
			<%= f.select :patient_id, options_from_collection_for_select(Patient.all, :id, :fullname), {:prompt => @patient_name}, {:class => 'form-control'} %>
			<% end %>
		</div>
	</div>
	<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
		<div class="form-group">
			<label>Appointment Date</label>
			<%= f.text_field :appointment_date, class: 'form-control' %>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
		<div class="form-group">
			<label>Treatment/Procedures</label>
			<%= f.text_area :purpose, class: 'form-control' %>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
		<div class="panel panel-default">
			<div class="panel-body">
				<label>Services</label>
				<br/>
				<%= hidden_field_tag "appointment[product_ids][]", nil %>
					<% Product.all.each do |p| %>
					<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
					<%= check_box_tag "appointment[product_ids][]", p.id, @appointment.product_ids.include?(p.id), id: dom_id(p) %>
					<%= label_tag dom_id(p), p.name %> <br>
					</div>
					<% end %>
			</div>
		</div>
	</div>
</div>
<div class="modal-footer">
	<div class="btn-group form-actions">
		<!--%= f.button :submit, value:'Save', class: 'btn btn-default' %-->
		<%= button_tag(type: 'submit', class: "btn btn-default lblinfo") do %>
		<span class='fa fa-book'></span> Set Appointment
		<% end %>
	</div>
</div>
<% end %>
<script type="text/javascript">
$(function () {
	$('#appointment_appointment_date').datetimepicker({
		format: 'YYYY-MM-DD HH:mm'
	});

});
</script>

app/views/appointment/_grid.html.erb
<%= define_grid(@appointment) do |g|
  g.row_attributes{ |appointment|
    {:id => "#{appointment.id}", :class=> "#{appointment.patient_id}", :style=>"cursor: pointer"}
  }
	g.column name: 'ID', attribute: 'id', detach_with_id: :id_filter

	g.column name: 'Date', attribute: 'appointment_date', detach_with_id: :date_filter do |d|
		d.appointment_date.strftime("%D")
	end

	g.column name: 'Name', attribute: "lname", model: 'Patient', detach_with_id: :name_filter do |n|
		n.patient.fullname
	end

	g.column name: 'Purpose', attribute: 'purpose', detach_with_id: :purpose_filter do  |p|
		truncate(p.purpose)
	end

	g.column name: 'Result', attribute: 'result', detach_with_id: :result_filter 

	g.column name: 'Remarks', attribute: 'remarks', detach_with_id: :remarks_filter


end -%>

app/views/appointment/_new.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
  	<span style="color: #fff" aria-hidden="true">&times;</span>
  </button>
  <span style="font-size: 16px">Set Appointment</span>
</div>
<div class="modal-body">
<%= render 'form' %>
</div>

app/views/appointment/_show.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span style="color: #fff" aria-hidden="true">&times;</span></button>
  <span style="font-size: 16px">Appointment</span>
</div>
<div class="modal-body">
<%= render 'form' %>
	
</div>

app/views/appointment/calendar.html.erb
<div id="calendar"></div>

<script type="text/javascript">
$(document).ready(function () {
	
	$('#calendar').fullCalendar({
		events: <%= raw(@events) %>,

		eventClick: function(event) {
			if (event.url) {
				// window.open(event.url);
				window.open(event.url,'winname',"directories=0,titlebar=0,toolbar=0,location=0,status=0,menubar=0,scrollbars=no,resizable=no,width=400,height=600");
				return false;
			}
		},
		eventColor: '#FF4209',
		fixedWeekCount: false,
		handleWindowResize: false
	});
});
</script>

app/views/appointment/create.html.erb
<h1>Appointment#create</h1>
<p>Find me in app/views/appointment/create.html.erb</p>

app/views/appointment/destroy.html.erb
<h1>Appointment#destroy</h1>
<p>Find me in app/views/appointment/destroy.html.erb</p>

app/views/appointment/edit.html.erb
<h1>Appointment#edit</h1>
<p>Find me in app/views/appointment/edit.html.erb</p>

app/views/appointment/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9 ">
      <h1>Today's Appointments</h1>
      <h5><%= Time.now.strftime("%A - %B %d, %Y ") %></h5>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
      <div class="form-inline pull-right">
        <br>    <%= link_to raw('<span class="glyphicon glyphicon-hand-right"></span> Set Appointment'), new_appointment_path, class: 'btn btn-default btn-sm', remote: true, data: { toggle: 'modal', target: "#appointment"}, title: 'Set Appointment' %>
        <%= link_to raw('<span class="glyphicon glyphicon-calendar"></span> Calendar'), appointment_calendar_path, class: 'btn btn-default btn-sm', data: { toggle: 'tooltip', placement: 'bottom'}, title: 'Show Appointment Calendar', target: :_blank %>
      </div>
    </div>
  </div>
  <table id="tblappointment" class="table table-hover table-condensed">
   <thead>
    <tr>
     <th>No.</th>
     <!-- <th>Date</th> -->
     <th>Patient</th>
     <th>Treatment</th>
     <th>Remarks</th>
   </tr>
 </thead>
 <tbody>
  <% i = 1 %>
  <% @appointment.each do |app| %>
  <tr data-link="<%= appointment_path(app.id) %>" id="<%= app.patient_id %>" style="cursor:pointer" data-toggle="tooltip" data-placement="bottom" title="Right click for options.">
   <td><%= i %></td>
   <!-- <td> --><!--%= app.appointment_date.strftime("%D") %--><!-- </td> -->
   <td><%= app.patient.lname.titlecase + ', ' + app.patient.fname.titlecase + ' ' + app.patient.mi.first.titlecase + '.' %></td>
   <td><%= truncate(app.purpose) %></td>
   <td><%= app.remarks %></td>
 </tr>
 <% i += 1 %>
 <% end %>
</tbody>
</table>
</div>
</div>
</div>
<div class="modal fade" tabindex="-1" role="dialog" id="appointment">
  <div class="modal-dialog">
    <div class="modal-content">
      <div id="appointment_content">
      </div>
    </div>
  </div>
</div>	

<ul id="contextMenu" class="dropdown-menu" role="menu" style="display:none" >
  <li><%= link_to raw("<span class='glyphicon glyphicon-pencil'></span> Edit"), "#", remote: true, data: { toggle: 'modal', target: "#appointment" }, title: 'Edit Appointment', id: 'm_edit' %></li>
  <li><%= link_to raw("<span class='glyphicon glyphicon-user'></span> Patient Info"), "#", title: 'View Patient Info', id: 'm_view' %></li>
  <li><%= link_to raw("<span class='glyphicon glyphicon-trash'></span> Delete"), "#", method: :delete, data: { confirm: "Remove appointment?" }, title: 'Remove Appointment', id: 'm_delete' %></li>
</ul>
<script type="text/javascript">
(function ($, window) {
  $.fn.contextMenu = function (settings) {
    return this.each(function () {
      $(this).on("contextmenu", function (e) {
        if (e.ctrlKey) return;
        // var pId = this.id;
        // var cId = $(this).attr("class");
        var cId = this.id;
        $("#m_edit").attr("href",$(this).data("link"));
        $("#m_view").attr("href","patient/"+cId);
        $("#m_delete").attr("href",$(this).data("link"));
        var $menu = $(settings.menuSelector)
        .data("invokedOn", $(e.target))
        .show()
        .css({
          position: "absolute",
          left: getMenuPosition(e.clientX, 'width', 'scrollLeft'),
          top: getMenuPosition(e.clientY, 'height', 'scrollTop')
        })
        .off('click')
        .on('click', 'a', function (e) {
          $menu.hide();
          var $invokedOn = $menu.data("invokedOn");
          var $selectedMenu = $(e.target);
                        // settings.menuSelected.call(this, $invokedOn, $selectedMenu,$patID);
                      });

        return false;
      });

      $(document).click(function () {
        $(settings.menuSelector).hide();
      });
    });

function getMenuPosition(mouse, direction, scrollDir) {
  var win = $(window)[direction](),
  scroll = $(window)[scrollDir](),
  menu = $(settings.menuSelector)[direction](),
  position = mouse + scroll;

  if (mouse + menu > win && menu < mouse) 
    position -= menu;

  return position;
}    

};
})(jQuery, window);


$("#tblappointment tr").contextMenu({
  menuSelector: "#contextMenu",
  menuSelected: function (invokedOn, selectedMenu, patID) {
    var msg = "You selected the menu item '" + selectedMenu.text() +
    "' on the value '" + invokedOn.text() + patId +"'";
        // var pid = $("#tblpatients tr").id();
        //   $("#view").attr("href").val("patients/")
        alert(msg);
      }
    });
</script>
<!-- <script src="https://cdn.datatables.net/1.10.4/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/plug-ins/9dcbecd42ad/integration/jqueryui/dataTables.jqueryui.js">
</script>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
<link rel="stylesheet" href="https://cdn.datatables.net/plug-ins/9dcbecd42ad/integration/jqueryui/dataTables.jqueryui.css"> -->
<script type="text/javascript">
$(document).ready(function(){
  // $("tr").click(function() {
  //   window.location = $(this).data("link");
  // });
  $('[data-toggle="tooltip"]').tooltip();

  $('#tblappointment').DataTable({
    bdestroy: true,
    sPaginationType: "full_numbers",
    bJqueryUI: true,
    // sDom: '<"H"Tl>tS<"F"ip>'
  });
});
</script>

app/views/appointment/index1.html.erb
<%= render 'grid' %>
<div class="show-panel">
  <div class="row">
    <div class="col-xs-7">
      <h1>Today's Appointments</h1>
      <h5><%= Time.now.strftime("%A - %B %d, %Y ") %></h5>
    </div>
    <div class="col-xs-5">
      <div class="pull-right">
        <div class="form-group form-inline">
          <br>
          <div class="panel panel-default panel-body">
            <label>Search</label>
            <br /> 
              <%= grid_filter @appointment, :name_filter %>
              <%= link_to raw('<span class="glyphicon glyphicon-hand-right"></span> Set'), new_appointment_path, class: 'btn btn-default btn-sm', remote: true, data: { toggle: 'modal', target: "#appointment"}, title: 'Set Appointment' %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row-fluid">
    <%= render_grid(@appointment) %>
  </div>
</div>
<div class="modal fade" tabindex="-1" role="dialog" id="appointment">
  <div class="modal-dialog">
    <div class="modal-content">
      <div id="appointment_content">
      </div>
    </div>
  </div>
</div>	

<ul id="contextMenu" class="dropdown-menu" role="menu" style="display:none" >
  <li><%= link_to raw("<span class='glyphicon glyphicon-pencil'></span> Edit"), "#", remote: true, data: { toggle: 'modal', target: "#appointment" }, title: 'Edit Appointment', id: 'm_edit' %></li>
  <li><%= link_to raw("<span class='glyphicon glyphicon-user'></span> Patient Info"), "#", title: 'View Patient Info', id: 'm_view' %></li>
  <li><%= link_to raw("<i class='fa fa-line-chart'></i> Statistics"), "#", title: 'View Patient Info', id: 'm_stat' %></li>
  <li><%= link_to raw("<span class='glyphicon glyphicon-trash'></span> Delete"), "#", method: :delete, data: { confirm: "Remove appointment?" }, title: 'Remove Appointment', id: 'm_delete' %></li>
</ul>
<script type="text/javascript">
(function ($, window) {
  $.fn.contextMenu = function (settings) {
    return this.each(function () {
      $(this).on("contextmenu", function (e) {
        if (e.ctrlKey) return;
        var pId = this.id;
        var cId = $(this).attr("class");
        $("#m_edit").attr("href","appointment/"+pId);
        $("#m_view").attr("href","patient/"+cId);
        $("#m_delete").attr("href","appointment/"+pId);
        var $menu = $(settings.menuSelector)
        .data("invokedOn", $(e.target))
        .show()
        .css({
          position: "absolute",
          left: getMenuPosition(e.clientX, 'width', 'scrollLeft'),
          top: getMenuPosition(e.clientY, 'height', 'scrollTop')
        })
        .off('click')
        .on('click', 'a', function (e) {
          $menu.hide();
          var $invokedOn = $menu.data("invokedOn");
          var $selectedMenu = $(e.target);
                        // settings.menuSelected.call(this, $invokedOn, $selectedMenu,$patID);
                      });

        return false;
      });

      $(document).click(function () {
        $(settings.menuSelector).hide();
      });
    });

function getMenuPosition(mouse, direction, scrollDir) {
  var win = $(window)[direction](),
  scroll = $(window)[scrollDir](),
  menu = $(settings.menuSelector)[direction](),
  position = mouse + scroll;

  if (mouse + menu > win && menu < mouse) 
    position -= menu;

  return position;
}    

};
})(jQuery, window);


$(".table tbody tr").contextMenu({
  menuSelector: "#contextMenu",
  menuSelected: function (invokedOn, selectedMenu, patID) {
    var msg = "You selected the menu item '" + selectedMenu.text() +
    "' on the value '" + invokedOn.text() + patId +"'";
        // var pid = $("#tblpatients tr").id();
        //   $("#view").attr("href").val("patients/")
        alert(msg);
      }
    });
</script>

app/views/appointment/new.js.erb
$('#appointment_content').html("<%= escape_javascript(render 'new') %>");

app/views/appointment/show.js.erb
$('#appointment_content').html("<%= escape_javascript(render 'show') %>");	

app/views/appointment/update.html.erb
<h1>Appointment#update</h1>
<p>Find me in app/views/appointment/update.html.erb</p>