config/routes.rb
PIS::Application.routes.draw do

  get "appointment/calendar"
  post "patient/create"
  get "users/sign_out"
  get "welcome/new"

  devise_for :users
  resources :patient
  resources :patient do
    member do
      resources :information
      get "set_appointment"
      post "update"
      get "edit_image"
      patch "update_image"
    end
  end
  resources :appointment, as: 'appointments'
  root 'patient#startup'

end

app/models/patient.rb
class Patient < ActiveRecord::Base
	belongs_to :user
	has_one :information
	# has_many :statistic
	has_many :appointments
	# has_many :diagnosis
	has_attached_file :image, styles: { small: "150x150>" }
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  	# accepts_nested_attributes_for :information, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
	accepts_nested_attributes_for :information, :allow_destroy => true

  	def fullname
  		lname + ', ' + fname + ' ' + mi
  	end
end

app/controllers/patient_controller.rb
class PatientController < ApplicationController
 before_action :find_patient, only: [:show, :edit, :update, :destroy, :edit_image, :update_image]
 before_action :authenticate_user!, :except=> [:startup]

 def startup
  
 end
 
 def index
 	@patient = Patient.all

 end

 def show
 	# @diagnosis = Diagnosis.find(@patient)
 	@information = Information.where(:patient_id =>params[:id])
  @information.each do |i|
 	  @info_id = i.id
  end
  @info=Information.find(@info_id)
  @appointment = Appointment.where(:patient_id=>params[:id])
 end

 def new
 	# @patient = current_user.patient.build
  @patient = Patient.new
  @patient.build_information

 end

 def new_image
  # @patient = current_user.patient.build  
 end

 def create_image
  @patient = current_user.patient.build(image_params)
  if @patient.save
    flash[:alert]="<big><span class='glyphicon glyphicon-user'></span></big> Image uploaded."
    redirect_to :back
  else
    flash[:error]="<big><span class='glyphicon glyphicon-user'></span></big> image not added."
    render 'new_image'
  end
 end

 def update_image
  if @patient.update(image_params)
        flash[:alert]="<big><span class='glyphicon glyphicon-user'></span></big> Patient basic info updated."
    redirect_to @patient
  else
        flash[:error]="<big><span class='glyphicon glyphicon-user'></span></big> Error editing patient."
    render 'edit'
  end
 end

 def create
 	@patient = current_user.patient.build(patient_params)
  @p_id = @patient.id
  if @patient.save
    user = User.find(current_user.id)
      user.patient_id = @patient.id
    user.save
    flash[:alert]="<big><span class='glyphicon glyphicon-user'></span></big> New Patient added."
 		redirect_to @patient
 	else
      	flash[:error]="<big><span class='glyphicon glyphicon-user'></span></big> Patient not added."
 		render 'new'
 	end
 end

 def edit
 	
 end

 def edit_image
  
 end

 def update
 	if @patient.update(patient_params)
      	flash[:alert]="<big><span class='glyphicon glyphicon-user'></span></big> Patient basic info updated."
 		    redirect_to @patient
 	else
      	flash[:error]="<big><span class='glyphicon glyphicon-user'></span></big> Error editing patient."
 		render 'edit'
 	end
 end

 def destroy
 	@patient.destroy
 	Information.find(@patient).destroy
 	flash[:alert]="<big><span class='glyphicon glyphicon-trash'></span></big> Patient information removed..."
 	redirect_to '/patient'
 end

 def logout
 	session.clear
 	flash[:alert]="<big><span class='glyphicon glyphicon-user'></span></big> Thank you for using PIS..."
 	redirect_to root_path
 end

 def set_appointment
  @id = current_user.id
  @appointment = Appointment.new
  @patient = Patient.find(params[:id])
  @patient_name = @patient.fullname
  @mode = "Online Booking"
 end

 private

 def find_patient
 	@patient = Patient.find(params[:id])
 end

 def patient_params
 	params.require(:patient).permit(:lname, :fname, :mi, :address, :image, 
                                  information_attributes: [:status, :sex, :age, :bday,
                                        :occupation, :homephone,:businessphone, 
                                        :mobilephone, :referredby, :spouse])
 end

 def image_params
  params.require(:patient).permit(:image)
 end
 
end

app/views/patient/_edit.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span style="color: #fff" aria-hidden="true">&times;</span></button>
   <span style="font-size: 16px">Edit Basic Information</span>
</div>
	<div class="modal-body">
		<%= render 'form' %>
	</div>
</div>

app/views/patient/_edit_image.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span style="color: #fff" aria-hidden="true">&times;</span></button>
   <span style="font-size: 16px">Edit Image</span>
</div>

	<div class="modal-body">
		<%= render 'form_image' %>
	</div>
</div>

app/views/patient/_form.html.erb
<%= simple_form_for @patient, wrapper: :pis_form, wrapper_mappings: { pis: :pis_form, file: :vertical_file_input, mi: :pis_form_small } do |f| %>
	<!-- <div class="row">
		<div class="col-xs-9">
		Choose Picture
		<!--%= f.file_field :image, class: 'form-control' %-->
		<!--</div>
	</div>
	<br /> -->
	<div class="row">
		<div class="col-xs-4">
			First Name
			<%= f.text_field :fname, class: 'form-control' %>
		</div>
		<div class="col-xs-4">
			Middle Name
			<%= f.text_field :mi, class: 'form-control' %>
		</div>
		<div class="col-xs-4">
			Last Name
			<%= f.text_field :lname, class: 'form-control' %>
		</div>
	</div>
	<br />
	<div class="row">
		<div class="col-xs-12">
			Address:
			<%= f.text_area :address, class: 'form-control' %>
		</div>
	</div>
	
	<br/>
<div class="modal-footer">
<div class="btn-group form-actions">
	<!--%= f.button :submit, class: 'btn btn-default' %-->
	<%= button_tag(type: 'submit', class: "btn btn-default lblinfo") do %>
				<i class='glyphicon glyphicon-ok'></i> Update
			<% end %>
</div>
</div>
<% end %>

app/views/patient/_form_image.html.erb
<%= simple_form_for @patient, url: update_image_patient_path, wrapper: :pis_form, wrapper_mappings: { pis: :pis_form, file: :vertical_file_input, mi: :pis_form_small } do |f| %>
	<div class="row">
		<div class="col-xs-9">
		Choose Picture
		<%= f.file_field :image, required: true, class: 'form-control' %>
		</div>
	</div>
	<br />
	
<div class="modal-footer">
	<%= f.button :submit, value:'Update', class: 'btn btn-default lblinfo' %>
</div>
<% end %>

app/views/patient/_forminfo.html.erb
<%= simple_form_for(@info, html: { class: 'form-horizontal' }) do |f| %>
<div class="form-horizontal">
	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
			<div class="form-group">
				<%= f.label :occupation, nil, class: 'control-label col-xs-5 col-sm-5 col-md-4 col-lg-4', style: 'text-align: left' %>
				<div class="col-xs-7 col-sm-7 col-md-8 col-lg-8">
					<%= f.text_field :occupation, class: 'form-control input-sm', autofocus: true %>
				</div>
			</div>
		</div>
		<div class="col-xs-12 col-sm-12 col-lg-4 col-md-4">
			<div class="form-group">
				<%= f.label :bday, 'Birth Date', class: 'pull-left col-xs-5 col-sm-5 col-md-4 col-lg-4', style: 'text-align: left' %>
				<div class="col-xs-7 col-sm-7 col-md-8 col-lg-8">
					<%= f.text_field :bday, class: 'form-control input-sm' %>
				</div>
			</div>
		</div>
		<div class="col-xs-12 col-sm-12 col-lg-4 col-md-4">
			<div class="form-group">
				<%= f.label :age, nil, class: 'pull-left col-xs-5 col-sm-5 col-md-4 col-lg-4', style: 'text-align: left' %>
				<div class="col-xs-7 col-sm-7 col-md-8 col-lg-8">
					<%= f.text_field :age, class: 'form-control input-sm' %>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
			<div class="form-group">
				<%= f.label :sex, nil, class: 'pull-left col-xs-5 col-sm-5 col-md-4 col-lg-4', style: 'text-align: left' %>
				<div class="col-xs-7 col-sm-7 col-md-8 col-lg-8">
					<%= f.select :sex, options_for_select([[ "Male", "Male"],["Female", "Female"]], @info.sex),{}, {class: 'form-control input-sm', style: 'font-size: 14px'} %>
				</div>
			</div>
		</div>
		<div class="col-xs-12 col-sm-12 col-lg-4 col-md-4">
			<div class="form-group">
				<%= f.label :status, 'Status', class: 'pull-left col-xs-5 col-sm-5 col-md-4 col-lg-4', style: 'text-align: left' %>
				<div class="col-xs-7 col-sm-7 col-md-8 col-lg-8">
					<%= f.select :status, options_for_select([[ "Single", "Single"],["Married", "Married"],["Separated", "Separated"],["Widow(er)", "Widow(er)"]], @info.status),{}, {class: 'form-control', style: 'font-size: 14px'} %>
				</div>
			</div>
		</div>
		<div class="col-xs-12 col-sm-12 col-lg-4 col-md-4">
			<div class="form-group">
				<%= f.label :spouse, nil, class: 'pull-left col-xs-5 col-sm-5 col-md-4 col-lg-4', style: 'text-align: left' %>
				<div class="col-xs-7 col-sm-7 col-md-8 col-lg-8">
					<%= f.text_field :spouse, class: 'form-control input-sm' %>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
			<div class="form-group ">
				<%= f.label :mobilephone, 'Mobile No.', class: 'pull-left col-xs-5 col-sm-5 col-md-4 col-lg-4', style: 'text-align: left' %>
				<div class="col-xs-7 col-sm-7 col-md-8 col-lg-8">
					<%= f.text_field :mobilephone, class: 'form-control input-sm' %>
				</div>
			</div>
		</div>
		<div class="col-xs-12 col-sm-12 col-lg-4 col-md-4">
			<div class="form-group">
				<%= f.label :businessphone, 'Business No.', class: 'pull-left col-xs-5 col-sm-5 col-md-4 col-lg-4', style: 'text-align: left' %>
				<div class="col-xs-7 col-sm-7 col-md-8 col-lg-8">
					<%= f.text_field :businessphone, class: 'form-control input-sm' %>
				</div>
			</div>
		</div>
		<div class="col-xs-12 col-sm-12 col-lg-4 col-md-4">
			<div class="form-group">
				<%= f.label :homephone, 'Home Phone', class: 'pull-left col-xs-5 col-sm-5 col-md-4 col-lg-4', style: 'text-align: left' %>
				<div class="col-xs-7 col-sm-7 col-md-8 col-lg-8">
					<%= f.text_field :homephone, class: 'form-control input-sm' %>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
			<div class="form-group">
				<%= f.label :referredby, 'Referred by', class: 'pull-left col-xs-5 col-sm-5 col-md-4 col-lg-4', style: 'text-align: left' %>
				<div class="col-xs-7 col-sm-7 col-md-8 col-lg-8">
					<%= f.text_field :referredby, class: 'form-control input-sm' %>
				</div>
			</div>
		</div>
		<div class="col-xs-12 col-sm-12 col-lg-4 col-md-4">
		</div>
		<div class="col-xs-12 col-sm-12 col-lg-4 col-md-4">
			<div class="pull-right">
				<%= button_tag(type: 'submit', class: "btn btn-default btn-xs") do %>
				<i class='glyphicon glyphicon-ok'></i> Update
				<% end %>
				<%= link_to raw("<i class='glyphicon glyphicon-remove'></i> Cancel"), @patients, class: 'btn btn-danger btn-xs', id: 'back' %> 
			</div>
		</div>
	</div>
</div>
<% end %>

<script type="text/javascript">
$(function () {
	// var appoint_date = '2015-09-03';

	$('#information_bday').datetimepicker({
		format: 'YYYY-MM-DD'
		// defaultDate: appoint_date
	});
	$('#information_bday').on('input', function(){
		
		alert('hey'); 
		// $('#information_age').val(age);

		// defaultDate: appoint_date
	});


	// $('#appointment_appointment_date').datetimepicker('update', new Date());
});


</script>

app/views/patient/_grid.html.erb
<%= define_grid(@grid) do |g|
        g.column name:  'ID', attribute: 'id', detach_with_id: :id_filter
        g.column name:  'LastName', attribute: 'lname', detach_with_id: :lname_filter
        g.column name:  'FirstName', attribute: 'fname', detach_with_id: :fname_filter
        g.column name:  'MI', attribute: 'mi', detach_with_id: :mi_filter
        g.column name:  'Address', attribute: 'address', detach_with_id: :add_filter
        g.column name: 'Action', attribute: 'address', detach_with_id: :action_filter do |g|
        	link_to raw('<span class="glyphicon glyphicon-user" aria-hidden="true"></span>'), patient_path(g.id), remote: true
        end
end -%>

app/views/patient/_information.html.erb
<% @information.each do |f| %>
	<h4 class="panel"><b>Personal Information</b></h4>
	<div class="row">
		<div class="col-xs-3">
			<label>Occupation</label>
			<label class="form-control"><%= f.occupation %></label>
		</div>
		<div class="col-xs-3">
			<label>Religion</label>
			<label class="form-control"><%= f.religion %></label>
		</div>
		<div class="col-xs-3">
			<label>Civil Status</label>
			<label class="form-control"><%= f.status %></label>
		</div>
		<div class="col-xs-3">
			<label>Sex</label>
			<label class="form-control"><%= f.sex %></label>
		</div>
	</div>
	<br />
	<div class="row">
		<div class="col-xs-3">
			<label>Birth Date</label>
		</div>
		<div class="col-xs-3">
			<label>Age</label>
		</div>
		<div class="col-xs-3">
			<label>Height</label>
		</div>
		<div class="col-xs-3">
			<label>Weight</label>
		</div>
	</div>
	<br />
	<h4><u><b>Contact Numbers</b></u></h4>
	<div class="row">
		<div class="col-xs-3">
			<label>Home</label>
		</div>
		<div class="col-xs-3">
			<label>Business</label>
		</div>
		<div class="col-xs-3">
			<label>Mobile No.</label>
		</div>
		<div class="col-xs-3">
			<label>Email</label>
		</div>
	</div>
	<br/>
</div>
<% end %>

app/views/patient/index.html.erb
<div class="show-panel">
  <br />
  <div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-md-2 col-lg-2">  <!-- style="height: 500px; border: 1px solid #eeeeee; border-radius: 5px" -->
      <%= render 'layouts/sidebar' %>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-10 col-lg-10">
      <!-- <div class="panel panel-default panel-body"> -->
      <table id="tblpatients" class="table table-hover">
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Address</th>
          </tr>
        </thead>
        <tbody>
          <% @patient.each do |patient| %>
          <tr data-link="<%= patient_path(patient.id) %>" data-remote="true" class="patient_info" style="cursor:pointer">
            <td><%= patient.id %></td>
            <td><%= patient.fullname %></td>
            <td><%= patient.address %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
jQuery(function($) {
  $('#tblpatients').DataTable({
    sPaginationType: "full_numbers",
    bJqueryUI: true,
    bdestroy: true
    // sDom: '<"H"Tl>tS<"F"ip>'
  });
});
$(document).ready(function(){

  $("tr").click(function() {
    window.location = $(this).data("link");
  });
});


</script>

app/views/patient/new.js.erb
$('#viewdialog').html("<%= escape_javascript(render 'new') %>");
// $('html').css('overflow-y','hidden');
// $('html').load().css('overflow-y','scroll');

app/views/patient/set_appointment.js.erb
$('#appointment_content').html("<%= escape_javascript(render 'set_appointment') %>");

app/views/patient/show.html.erb
<% @information.each do |f| %>
<div class="container">
	<div class="clearfix">
		<br>
		<div>
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-3 col-lg-2 ">
					<div class="thumbnail">
						<div class="caption">
							<h4>Image</h4>
							<p>Change Picture</p>
							<br>
							<p>
								<%= link_to raw('<i class="glyphicon glyphicon-paperclip"></i> Upload here'), edit_image_patient_path(@patient), class: 'label label-danger lbl-lg', rel: 'tooltip', remote: true, data: { toggle: 'modal', target: "#view" } %>
							</p>	
						</div>
						<%= image_tag @patient.image.url(:small), class: 'img-responsive', style: 'height: 150px; cursor: pointer' %>
					</div>
				</div>
				<div class="col-xs-12 col-sm-12 col-md-9 col-lg-10">
					<div class="row">
						<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
							<span style="font-size:2em; font-weight: bold; color: #FF4209"><%= @patient.lname + ', ' + @patient.fname + ' ' + @patient.mi  %></span>
							<p><%= @patient.address %></p>
							<div class="hidden-xs hidden-sm">
								<br><br><br>
							</div>
							<p style="font-size: 12px">
								<span class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
									<span class="glyphicon glyphicon-list-alt"></span> Program Started: <span class="lbldates"><%= f.dps.strftime("%D") if f.dps %></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
								</span> 
								<span class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
									<span class="glyphicon glyphicon-user"></span> Profile Updated: <span class="lbldates"><%= @patient.updated_at.strftime("%D") %></span>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;
								</span> 
								<span class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
									<span class="glyphicon glyphicon-pushpin"></span> Last Visit: <span class="lbldates"><%= @patient.updated_at.strftime("%D") %></span>
								</span> 
							</p>	

						</div>
						<div>
							<span class="btn btn-group pull-right">
								<%= link_to raw("<i class='fa fa-reply'></i>"), "/patient", class: 'btn btn-default', title: 'Back to Lists' %>
								<%= link_to raw('<i class="glyphicon glyphicon-pencil"></i>'), edit_patient_path(@patient), class: 'btn btn-default', remote: true, data: { toggle: 'modal', target: "#view" }, title: 'Edit Basic Info' %>
								<%= link_to raw("<i class='glyphicon glyphicon-edit'></i>"), set_appointment_patient_path(@patient.id), class: 'btn btn-default', remote: true, data: {toggle: 'modal', target: '#appointment'}, title: 'Set Appointment' %> 
								<%= link_to raw('<i class="glyphicon glyphicon-trash"></i>'), patient_path(@patient), method: :delete,  class: 'btn btn-default', data: { confirm: 'Are you sure you want to delete this patient?'}, title: 'Delete Patient' %>
							</span>
						</div>
						

					</div>
				</div>
			</div>
		</div>

		<div class="panel panel-default panel-style">
			<div class="panel-body">
				<span style="font-size: 1.2em;"><i class="fa fa-street-view fa-lg iconheader"></i> <strong>Personal Information</strong></span>
				<span class="pull-right">
					<div>
						<!-- <a class="lblinfo" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="cursor:pointer">
							<span class="glyphicon glyphicon-chevron-down"></span>
							<span class="caret"></span>
						</a> -->
						<!-- <ul class="dropdown-menu"> -->
						<!-- <li> -->
						<% if current_user.role == "admin" %>
						<%= link_to raw("<span class='glyphicon glyphicon-pencil'></span> Edit"), '#', class: 'lblinfo', id: 'infox', title: 'Edit Patient' %>
						<% end %>
						<!-- </li> -->
						<!-- <li role="separator" class="divider"></li> -->
						<!-- </ukl> -->
					</div>
				</span>
			</div>
			<div id="show" class="panel-body">
				<div class="form-horizontal">
					<div class="row">
						<div class="col col-xs-12 col-sm-12 col-lg-4 col-md-4">
							<div class="form-group">
								<%= label_tag :occupation,'Occupation', class: 'pull-left col-xs-5 col-sm-5 col-md-4 col-lg-4', style: 'text-align: left' %>
								<div class="col-xs-7 col-sm-7 col-md-8 col-lg-8">
									<span class="form-control lblinfo"><%= f.occupation %></span>
								</div>
							</div>
						</div>
						<div class="col col-xs-12 col-sm-12 col-lg-4 col-md-4">
							<div class="form-group">
								<%= label_tag :bday, 'Birth Date', class: 'pull-left col-xs-5 col-sm-5 col-md-4 col-lg-4', style: 'text-align: left' %>
								<div class="col-xs-7 col-sm-7 col-md-8 col-lg-8">
									<span class="form-control lblinfo"><%= f.bday %></span>
								</div>
							</div>
						</div>
						<div class="col col-xs-12 col-sm-12 col-lg-4 col-md-4">
							<div class="form-group">
								<%= label_tag :age, nil, class: 'pull-left col-xs-5 col-sm-5 col-md-4 col-lg-4', style: 'text-align: left' %>
								<div class="col-xs-7 col-sm-7 col-md-8 col-lg-8">
									<span class="form-control lblinfo"><%= f.age %></span>
								</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col col-xs-12 col-sm-12 col-lg-4 col-md-4">
							<div class="form-group">
								<%= label_tag :sex, nil, class: 'pull-left col-xs-5 col-sm-5 col-md-4 col-lg-4', style: 'text-align: left' %>
								<div class="col-xs-7 col-sm-7 col-md-8 col-lg-8">
									<span class="form-control lblinfo"><%= f.sex %></span>
								</div>
							</div>
						</div>
						<div class="col col-xs-12 col-sm-12 col-lg-4 col-md-4">
							<div class="form-group">
								<%= label_tag :status, 'Status', class: 'pull-left col-xs-5 col-sm-5 col-md-4 col-lg-4', style: 'text-align: left' %>
								<div class="col-xs-7 col-sm-7 col-md-8 col-lg-8">
									<span class="form-control lblinfo"><%= f.status %></span>
								</div>
							</div>
						</div>
						<div class="col col-xs-12 col-sm-12 col-lg-4 col-md-4">
							<div class="form-group">
								<%= label_tag :spouse, nil, class: 'pull-left col-xs-5 col-sm-5 col-md-4 col-lg-4', style: 'text-align: left' %>
								<div class="col-xs-7 col-sm-7 col-md-8 col-lg-8">
									<span class="form-control lblinfo"><%= f.spouse %></span>
								</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col col-xs-12 col-sm-12 col-lg-4 col-md-4">
							<div class="form-group">
								<%= label_tag :mobilephone, 'Mobile No.', class: 'pull-left col-xs-5 col-sm-5 col-md-4 col-lg-4', style: 'text-align: left' %>
								<div class="col-xs-7 col-sm-7 col-md-8 col-lg-8">
									<span class="form-control lblinfo"><%= f.mobilephone %></span>
								</div>
							</div>
						</div>
						<div class="col col-xs-12 col-sm-12 col-lg-4 col-md-4">
							<div class="form-group">
								<%= label_tag :businessphone, 'Business No.', class: 'pull-left col-xs-5 col-sm-5 col-md-4 col-lg-4', style: 'text-align: left' %>
								<div class="col-xs-7 col-sm-7 col-md-8 col-lg-8">
									<span class="form-control lblinfo"><%= f.businessphone %></span>
								</div>
							</div>
						</div>
						<div class="col col-xs-12 col-sm-12 col-lg-4 col-md-4">
							<div class="form-group">
								<%= label_tag :homephone, 'Home Phone', class: 'pull-left col-xs-5 col-sm-5 col-md-4 col-lg-4', style: 'text-align: left' %>
								<div class="col-xs-7 col-sm-7 col-md-8 col-lg-8">
									<span class="form-control lblinfo"><%= f.homephone %></span>
								</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col col-xs-12 col-sm-12 col-lg-4 col-md-4">
							<div class="form-group">
								<%= label_tag :referredby, 'Referred by', class: 'pull-left col-xs-5 col-sm-5 col-md-4 col-lg-4', style: 'text-align: left' %>
								<div class="col-xs-7 col-sm-7 col-md-8 col-lg-8">
									<span class="form-control lblinfo"><%= f.referredby %></span>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="panel panel-default panel-style">
			<div class="panel-body">
				<span style="font-size:18px; "><i class="fa fa-line-chart fa-lg iconheader"></i> <strong>Appointment History</strong></span>
			</div>
			<div class="panel-body">
				<table class="table table-hover table-responsive">
					<thead>
						<tr>
							<th>#</th>
							<th>Date</th>
							<th>Services</th>
							<!-- <th>Result</th> -->
							<th>Remarks</th>
						</tr>
					</thead>
					<tbody>
						<% i = 1 %>
						<% @appointment.each do |app| %>
						<tr id='<%= app.id %>' style="cursor:pointer">
							<td><%= i %></td>
							<td><%= app.appointment_date.strftime("%D") %></td>
							<td><%= truncate(app.purpose) %></td>
							<!-- <td> --><!--%= app.result %--><!-- </td> -->
							<td><%= app.remarks %></td>
						</tr>
						<% i += 1 %>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
		<div class="panel panel-default panel-style">
			<div class="panel-body">
				<span style="font-size:18px; "><i class="fa fa-bar-chart fa-lg iconheader"></i> <strong>Statistics</strong></span>
			</div>
			<div class="panel-body">

			</div>
		</div>		
	</div>
</div>	
<% end %>
<div class="modal fade" tabindex="-1" role="dialog" id="appointment">
	<div class="modal-dialog">
		<div class="modal-content">
			<div id="appointment_content">
			</div>
		</div>
	</div>
</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	$('#infox').click(function(){
		// $('#show').hide();
		$('#show').html("<%= escape_javascript(render 'forminfo') %>");
		$('#infox').hide();
		// $('#show').fadeIn();
	});

	$('#edit_information_<%= params[:id] %>').submit(function(event) {
		event.preventDefault();
		var form = $(this);
		$.ajax({
			type: 'POST',
			url: '<%= information_path(params[:id]) %>',
			data: form.serialize(),
		//processData: false,
		//contentType: false,
		success: function(){
			alert('Data updated!');
		},
	});
	});

	$("[rel='tooltip']").tooltip();    

	$('.thumbnail').hover(
		function(){
        $(this).find('.caption').slideDown(250); //.fadeIn(250)
    },
    function(){
        $(this).find('.caption').slideUp(250); //.fadeOut(205)
    }
    ); 
});
</script>