config/routes.rb
PIS::Application.routes.draw do

  get "appointment/calendar"
  post "patient/create"
  get "users/sign_out"
  get "welcome/new"

  devise_for :users
  resources :patient
  resources :patient do
    member do
      resources :information
      get "set_appointment"
      post "update"
      get "edit_image"
      patch "update_image"
    end
  end
  resources :appointment, as: 'appointments'
  root 'patient#startup'

end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>

  <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 pull-left alert <%= alert_class_for(type) %> alert-dismissible fade in">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= message.html_safe %>
    
  </div>
<% end %>
<script>
	setTimeout("$('.alert').fadeOut('slow')", 5000)
</script>

app/views/layouts/_sidebar.html.erb
 <div class="panel panel-danger hidden-sm hidden-xs">
  <div class="panel-heading">
    <h3 class="panel-title">
      Patients
    </h3>
  </div>
  <ul class="list-group">
    <li class="list-group-item">
      <i class="fa fa-stethoscope fa-xs"></i> No of Patients
    </li>
    <li class="list-group-item">
      <%= link_to raw('<i class="fa fa-plus fa-sm"></i> Add Patient'), new_patient_path, remote: true, data: { toggle: 'modal', target: "#view" } %>
    </li>
    <li class="list-group-item">
      <i class="fa fa-user-md fa-xs"></i> Doctor(s)
    </li>
  </ul>
</div>

<div class="container hidden-md hidden-lg">
  <i class="fa fa-stethoscope fa-xs"></i> No of Patients | 
  <%= link_to raw('<i class="fa fa-plus fa-sm"></i> Add Patient'), new_patient_path, remote: true, data: { toggle: 'modal', target: "#view" } %> | 
  <i class="fa fa-user-md fa-xs"></i> Doctor(s)
  <br/>
  <br/>

</div>

app/views/layouts/_sidebarold.html.erb
<div class="panel-group" id="accordion">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Statement no. 1</a>
            </h4>
          </div>
          <div id="collapseOne" class="panel-collapse collapse">
            <div class="panel-body">
              <p>HTML stands for HyperText Markup Language. HTML is the main markup language for describing the structure of Web pages. <a href="http://www.tutorialrepublic.com/html-tutorial/" target="_blank">Learn more.</a></p>
            </div>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">Statement no. 2</a>
            </h4>
          </div>
          <div id="collapseTwo" class="panel-collapse collapse">
            <div class="panel-body">
              <p>Bootstrap is a powerful front-end framework for faster and easier web development. It is a collection of CSS and HTML conventions. <a href="http://www.tutorialrepublic.com/twitter-bootstrap-tutorial/" target="_blank">Learn more.</a></p>
            </div>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">Statement No. 3</a>
            </h4>
          </div>
          <div id="collapseThree" class="panel-collapse collapse">
            <div class="panel-body">
              <p>CSS stands for Cascading Style Sheet. CSS allows you to specify various style properties for a given HTML element such as colors, backgrounds, fonts etc. <a href="http://www.tutorialrepublic.com/css-tutorial/" target="_blank">Learn more.</a></p>
            </div>
          </div>
        </div>
      </div>

app/views/layouts/_topbar.html.erb
<% @appcount=Appointment.where("DATE(appointment_date) ='#{Date.today}'").count(:id) %>
<nav class="navbar navbar-inverse navbar-fixed-top" style="background-color: #0E0E29; border: none">
  <div class="container">
    <div class="row">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navcollapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <span class="navbar-brand" style="color: #F1EAEA"><%= image_tag 'NCI.png', style: 'height: 30px; width: 45px' %> <span style="font-size: .8em"><!-- Sample Application Inc. --> Natural Complexions Inc.</span></span>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->

      <div class="collapse navbar-collapse" id="navcollapse">
        <ul class="nav nav-pills navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="<%= 'active' if request.path=='/' %>" data-toggle="tooltip" data-placement="bottom" title="Home">
              <%= link_to raw('<span class="fa fa-home fa-lg"></span>'), root_path %> 
            </li>
            <li class="<%= 'active' if request.path=='/patient/'+ current_user.patient_id.to_s %>" data-toggle="tooltip" data-placement="bottom" title="Profile">
              <% if current_user.patient_id? %>
              <%= link_to raw('<span class="fa fa-user fa-lg"></span>'), patient_path(current_user.patient_id) %>
              <% else %>
               <%= link_to raw('<i class="fa fa-plus fa-sm"></i>'), new_patient_path, remote: true, data: { toggle: 'modal', target: "#view" } %>
              <% end %>
            </li>
            <% if current_user.role =="admin" %>
            <li class="<%= 'active' if request.path=='/patient' or request.path == '/patient/' + params[:id].to_s %>" data-toggle="tooltip" data-placement="bottom" title="Patients">
              <%= link_to raw('<span class="fa fa-user-md fa-lg"></span>'), patient_index_path %>
            </li>
            <li class="<%= 'active' if request.path=='/appointment' %>" data-toggle="tooltip" data-placement="bottom" title="Appointments">
              <%= link_to raw("<span class='fa fa-tasks fa-lg'></span><span class='badge'>#{@appcount}</span>"), appointments_path, data: {toogle: 'pill'} %>
            </li>
            <li><!--  data-toggle="tooltip" data-placement="bottom" title="Search" -->
              <%= link_to raw("<span class='fa fa-search fa-lg'></span>"), "#search", id: 'search', data: {toogle: 'popover', trigger: 'focus', content: 'Sample Search for popover', placement: 'bottom'}, title: 'Search patients', tabindex: "0" %>
              
            </li>
            <% end %>
          <li data-toggle="tooltip" data-placement="bottom" title="Logout">
            <%= link_to raw('<span class="fa fa-sign-out fa-lg"></span>'), destroy_user_session_path, :method => :delete, data: { confirm: "Are you sure you want to Logout?" } %>
          </li>
          <% else %>
          <li class="<%= 'active' if request.path=='/users/sign_in' %>">
            <%= link_to 'Login', new_user_session_path, data: { toogle: 'pill' } %>
          </li>
          <!-- <li class="<%#= 'active' if request.path=='/users/sign_up' %>"><%#= link_to 'Sign up', new_user_registration_path, data: {toogle: 'pill'} %></li> -->
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
  <div style="height: 5px; background-color: #FF4209">
  </div>
</nav>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>PIS</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body style="background-color: ##F3F3F3;">
  <div class="alert-fixed pull-right">
      <%= render partial: "layouts/flash", flash: flash %>
  </div>
	<!--% if user_signed_in? %-->
		  <%= render :partial=> 'layouts/topbar' %>
	<!--% end %-->
<br />
<br />
<br />
<div class="container">
	<div class="row" id="content">
		<%= yield %>
	</div>
</div>
<div class="modal fade" tabindex="-1" role="dialog" id="view">
  <div class="modal-dialog">
    <div class="modal-content">
      <div id="viewdialog">
        <!-- content dialog -->
      </div>
    </div>
  </div>
</div>
<script>

$('#search').click(function(){
  $('#search').popover();
})
</script>

<%= javascript_include_tag "jquery.dataTables.min" %>
<%= javascript_include_tag "dataTables.jqueryui" %>

<!--%= javascript_include_tag "dataTables.jqueryui" %-->
<%= stylesheet_link_tag "smoothness" %>
<%= stylesheet_link_tag "dataTables.jqueryui" %>

<!-- <script src="https://cdn.datatables.net/1.10.4/js/jquery.dataTables.min.js"></script> -->
<!-- <script src="https://cdn.datatables.net/plug-ins/9dcbecd42ad/integration/jqueryui/dataTables.jqueryui.js"></script> -->
<!-- <link rel="stylesheet" href="https://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css"> -->
<!-- <link rel="stylesheet" href="https://cdn.datatables.net/plug-ins/9dcbecd42ad/integration/jqueryui/dataTables.jqueryui.css"> -->
</body>
</html>